import { existsSync, mkdirSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { Config } from "../config.ts";
import type { ThreadSession } from "../session/types.ts";
import type { CodexApprovalPolicy, CodexSandbox } from "./policy.ts";
import { resolveEffectivePermissionIntent } from "../agents/loader.ts";
import { subjectHasCapability } from "../agents/capabilities.ts";
import {
  mixpanelMcpUrl,
  mongoMcpUrl,
  figmaMcpUrl,
  notionMcpUrl,
  playwrightMcpCommand,
  slackMcpUrl,
  wantsMcp,
} from "../runners/mcp-config.ts";

export interface CodexMcpServerConfig {
  transport?: "http";
  url?: string;
  command?: string;
  args?: string[];
  tools?: Record<string, CodexMcpToolConfig>;
}

export interface CodexMcpToolConfig {
  approval_mode: "approve";
}

export type CodexMcpConfig = Record<string, CodexMcpServerConfig>;

export function buildCodexMcpConfig(
  config: Config,
  session: ThreadSession,
  mcpAllowed: boolean,
): CodexMcpConfig | null {
  if (!config.codex.mcpEnabled || !mcpAllowed) return null;

  const mcp: CodexMcpConfig = {};

  if (config.codex.slackMcpEnabled && wantsMcp(session, "slack-bot")) {
    mcp["slack-bot"] = {
      transport: "http",
      url: slackMcpUrl(session),
      ...trustedMcpToolConfig(session, "slack-bot"),
    };
  }
  if (config.codex.playwrightMcpEnabled && wantsMcp(session, "playwright")) {
    mcp.playwright = {
      ...playwrightMcpCommand(),
      ...trustedMcpToolConfig(session, "playwright"),
    };
  }
  if (config.codex.mixpanelMcpEnabled && wantsMcp(session, "mixpanel") && isFeatureMetricsSession(session)) {
    mcp.mixpanel = {
      transport: "http",
      url: mixpanelMcpUrl(session),
      ...trustedMcpToolConfig(session, "mixpanel"),
    };
  }
  if (config.codex.mongodbMcpEnabled && wantsMcp(session, "mongodb")) {
    mcp.mongodb = {
      transport: "http",
      url: mongoMcpUrl(session),
      ...trustedMcpToolConfig(session, "mongodb"),
    };
  }
  if (config.codex.figmaMcpEnabled !== false && wantsMcp(session, "figma")) {
    mcp.figma = {
      transport: "http",
      url: figmaMcpUrl(),
      ...trustedMcpToolConfig(session, "figma"),
    };
  }
  if (config.codex.notionMcpEnabled !== false && wantsMcp(session, "notion")) {
    mcp.notion = {
      transport: "http",
      url: notionMcpUrl(),
      ...trustedMcpToolConfig(session, "notion"),
    };
  }

  return Object.keys(mcp).length > 0 ? mcp : null;
}

export function prepareCodexHome(options: {
  isolatedHomePath: string | null;
  model: string | null;
  reasoningEffort: string;
  approvalPolicy: CodexApprovalPolicy;
  sandbox: CodexSandbox;
  mcp: CodexMcpConfig | null;
  trustedProjectPath?: string;
}): string | null {
  const codexHome = options.isolatedHomePath
    ? resolve(options.isolatedHomePath)
    : null;
  if (!codexHome) return null;

  mkdirSync(codexHome, { recursive: true });
  const authPath = resolve(codexHome, "auth.json");
  const realAuthPath = resolve(process.env.CODEX_REAL_HOME ?? resolveHome(".codex"), "auth.json");
  if (!existsSync(authPath) && existsSync(realAuthPath)) {
    try {
      symlinkSync(realAuthPath, authPath);
    } catch {
      // A concurrent spawn may have created it.
    }
  }

  const configPath = resolve(codexHome, "config.toml");
  writeFileSync(configPath, buildCodexConfigToml(options), "utf8");
  mkdirSync(dirname(configPath), { recursive: true });

  const hooksPath = resolve(codexHome, "hooks.json");
  if (existsSync(hooksPath)) rmSync(hooksPath, { force: true });

  return codexHome;
}

export function buildCodexConfigToml(options: {
  model: string | null;
  reasoningEffort: string;
  approvalPolicy: CodexApprovalPolicy;
  sandbox: CodexSandbox;
  mcp: CodexMcpConfig | null;
  trustedProjectPath?: string;
}): string {
  const lines: string[] = [
    "# Generated by Junior. Do not add personal hooks, MCP servers, plugins, or skills here.",
  ];
  if (options.model) lines.push(`model = ${tomlString(options.model)}`);
  lines.push(`model_reasoning_effort = ${tomlString(options.reasoningEffort)}`);
  lines.push(`approval_policy = ${tomlString(options.approvalPolicy)}`);
  lines.push(`sandbox_mode = ${tomlString(options.sandbox)}`);
  lines.push("");
  lines.push("[features]");
  lines.push("multi_agent = false");
  // Junior supplies capability-scoped MCP tools. Do not inherit personal
  // Codex connected apps (for example GitHub) from the shared auth session.
  lines.push("apps = false");
  lines.push("");

  for (const [name, server] of Object.entries(options.mcp ?? {})) {
    lines.push(`[mcp_servers.${tomlBareKey(name)}]`);
    if (server.transport) lines.push(`transport = ${tomlString(server.transport)}`);
    if (server.url) lines.push(`url = ${tomlString(server.url)}`);
    if (server.command) lines.push(`command = ${tomlString(server.command)}`);
    if (server.args) {
      lines.push(`args = [${server.args.map(tomlString).join(", ")}]`);
    }
    for (const [toolName, tool] of Object.entries(server.tools ?? {})) {
      lines.push("");
      lines.push(
        `[mcp_servers.${tomlBareKey(name)}.tools.${tomlBareKey(toolName)}]`,
      );
      lines.push(`approval_mode = ${tomlString(tool.approval_mode)}`);
    }
    lines.push("");
  }

  if (options.trustedProjectPath) {
    lines.push(`[projects.${tomlString(options.trustedProjectPath)}]`);
    lines.push('trust_level = "trusted"');
    lines.push("");
  }

  return lines.join("\n");
}

function resolveHome(path: string): string {
  return resolve(process.env.HOME ?? process.cwd(), path);
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlBareKey(key: string): string {
  return /^[A-Za-z0-9_-]+$/.test(key) ? key : tomlString(key);
}

function isFeatureMetricsSession(session: ThreadSession): boolean {
  return (
    session.agentType === "feature-metrics" ||
    session.activeAgentName === "feature-metrics"
  );
}

/**
 * Codex's `approval_policy = "never"` also rejects MCP calls unless the MCP
 * tool has an explicit approval mode. Read-only Junior roles may use only the
 * MCP tools granted by their trusted definition/capabilities, so mark those
 * exact tools as approved while leaving shell/file approval unchanged.
 */
function trustedMcpToolConfig(
  session: ThreadSession,
  serverName: string,
): { tools: Record<string, CodexMcpToolConfig> } | Record<string, never> {
  const intent = resolveEffectivePermissionIntent(
    session.agentPermissions,
    session.activeAgentName ?? session.agentType,
  );
  if (intent !== "read-only" && intent !== "mcp-only") return {};

  const prefix = `mcp__${serverName}__`;
  const tools = new Set(
    (session.agentPermissions?.tools ?? [])
      .filter((tool) => tool.startsWith(prefix))
      .map((tool) => tool.slice(prefix.length)),
  );

  for (const [capability, capabilityTools] of Object.entries(CAPABILITY_MCP_TOOLS)) {
    if (subjectHasCapability(session, capability as Parameters<typeof subjectHasCapability>[1])) {
      for (const tool of capabilityTools) {
        if (tool.startsWith(prefix)) tools.add(tool.slice(prefix.length));
      }
    }
  }

  if (tools.size === 0) return {};
  return {
    tools: Object.fromEntries(
      [...tools].map((tool) => [tool, { approval_mode: "approve" }]),
    ),
  };
}

const CAPABILITY_MCP_TOOLS = {
  "github-review-read": ["mcp__slack-bot__github_read_pr_review_state"],
  "github-review-comment": ["mcp__slack-bot__github_post_review"],
  "pipeline-artifact-write": [
    "mcp__slack-bot__pipeline_get_state",
    "mcp__slack-bot__pipeline_write_artifact",
    "mcp__slack-bot__pipeline_report_outcome",
  ],
  "pipeline-run-start": ["mcp__slack-bot__pipeline_start_run"],
  "mongodb-read": [
    "mcp__mongodb__aggregate",
    "mcp__mongodb__count",
    "mcp__mongodb__find",
    "mcp__mongodb__list-databases",
    "mcp__mongodb__list-collections",
    "mcp__mongodb__collection-schema",
  ],
  dispatch: [
    "mcp__slack-bot__agent_dispatch",
    "mcp__slack-bot__skill_dispatch",
  ],
  "worktree-mutate": ["mcp__slack-bot__unregister_worktree"],
} as const;
