import { existsSync, mkdirSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { Config } from "../config.ts";
import type { ThreadSession } from "../session/types.ts";
import type { CodexApprovalPolicy, CodexSandbox } from "./policy.ts";
import {
  mixpanelMcpCommand,
  mongoMcpUrl,
  playwrightMcpCommand,
  slackMcpUrl,
  wantsMcp,
} from "../runners/mcp-config.ts";

export interface CodexMcpServerConfig {
  transport?: "http";
  url?: string;
  command?: string;
  args?: string[];
}

export type CodexMcpConfig = Record<string, CodexMcpServerConfig>;

export function buildCodexMcpConfig(
  config: Config,
  session: ThreadSession,
  mcpAllowed: boolean,
): CodexMcpConfig | null {
  if (!config.codex.mcpEnabled || !mcpAllowed) return null;

  const mcp: CodexMcpConfig = {};

  if (config.codex.slackMcpEnabled && wantsMcp(session, "slack-bot")) {
    mcp["slack-bot"] = {
      transport: "http",
      url: slackMcpUrl(session),
    };
  }
  if (config.codex.playwrightMcpEnabled && wantsMcp(session, "playwright")) {
    mcp.playwright = playwrightMcpCommand();
  }
  if (config.codex.mixpanelMcpEnabled && wantsMcp(session, "mixpanel") && isFeatureMetricsSession(session)) {
    mcp.mixpanel = mixpanelMcpCommand();
  }
  if (config.codex.mongodbMcpEnabled && wantsMcp(session, "mongodb")) {
    mcp.mongodb = {
      transport: "http",
      url: mongoMcpUrl(session),
    };
  }

  return Object.keys(mcp).length > 0 ? mcp : null;
}

export function prepareCodexHome(options: {
  isolatedHomePath: string | null;
  model: string | null;
  approvalPolicy: CodexApprovalPolicy;
  sandbox: CodexSandbox;
  mcp: CodexMcpConfig | null;
  trustedProjectPath?: string;
}): string | null {
  const codexHome = options.isolatedHomePath
    ? resolve(options.isolatedHomePath)
    : null;
  if (!codexHome) return null;

  mkdirSync(codexHome, { recursive: true });
  const authPath = resolve(codexHome, "auth.json");
  const realAuthPath = resolve(process.env.CODEX_REAL_HOME ?? resolveHome(".codex"), "auth.json");
  if (!existsSync(authPath) && existsSync(realAuthPath)) {
    try {
      symlinkSync(realAuthPath, authPath);
    } catch {
      // A concurrent spawn may have created it.
    }
  }

  const configPath = resolve(codexHome, "config.toml");
  writeFileSync(configPath, buildCodexConfigToml(options), "utf8");
  mkdirSync(dirname(configPath), { recursive: true });

  const hooksPath = resolve(codexHome, "hooks.json");
  if (existsSync(hooksPath)) rmSync(hooksPath, { force: true });

  return codexHome;
}

export function buildCodexConfigToml(options: {
  model: string | null;
  approvalPolicy: CodexApprovalPolicy;
  sandbox: CodexSandbox;
  mcp: CodexMcpConfig | null;
  trustedProjectPath?: string;
}): string {
  const lines: string[] = [
    "# Generated by Junior. Do not add personal hooks, MCP servers, plugins, or skills here.",
  ];
  if (options.model) lines.push(`model = ${tomlString(options.model)}`);
  lines.push(`approval_policy = ${tomlString(options.approvalPolicy)}`);
  lines.push(`sandbox_mode = ${tomlString(options.sandbox)}`);
  lines.push("");

  for (const [name, server] of Object.entries(options.mcp ?? {})) {
    lines.push(`[mcp_servers.${tomlBareKey(name)}]`);
    if (server.transport) lines.push(`transport = ${tomlString(server.transport)}`);
    if (server.url) lines.push(`url = ${tomlString(server.url)}`);
    if (server.command) lines.push(`command = ${tomlString(server.command)}`);
    if (server.args) {
      lines.push(`args = [${server.args.map(tomlString).join(", ")}]`);
    }
    lines.push("");
  }

  if (options.trustedProjectPath) {
    lines.push(`[projects.${tomlString(options.trustedProjectPath)}]`);
    lines.push('trust_level = "trusted"');
    lines.push("");
  }

  return lines.join("\n");
}

function resolveHome(path: string): string {
  return resolve(process.env.HOME ?? process.cwd(), path);
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlBareKey(key: string): string {
  return /^[A-Za-z0-9_-]+$/.test(key) ? key : tomlString(key);
}

function isFeatureMetricsSession(session: ThreadSession): boolean {
  return (
    session.agentType === "feature-metrics" ||
    session.activeAgentName === "feature-metrics"
  );
}
